# Generated by Django 4.1 on 2023-06-12 18:18

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_intervalgamestat_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalgamestat',
            name='stats',
            field=models.JSONField(default=main.models.get_default_intervals_stat),
        ),
    ]
