# Generated by Django 4.1 on 2023-08-09 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.helpers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_intervalgamestat_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChordGameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_incorrect', models.IntegerField(default=0)),
                ('stats', models.JSONField(default=main.helpers.get_default_chords_stat)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
